### ISSUE TITLE
'dict' object has no attribute 'base' error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [ShuhongChen/panic3d-anime-reconstruction#28]
The following error occurred.

```
$ python3 -m _scripts.eval.generate && python3 -m _scripts.eval.measure
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dl/panic3d/panic3d-anime-reconstruction/_scripts/eval/generate.py", line 29, in <module>
    dk = dklustr.DatabackendMinna()
  File "/home/dl/panic3d/panic3d-anime-reconstruction/_databacks/lustrous_renders_v1.py", line 116, in __init__
    self.dn = f'{self.args.base.dn}/_data/lustrous'
AttributeError: 'dict' object has no attribute 'base'
```

Please let me know how to fix it.

**Comment by ShuhongChen** [comment]
https://github.com/ShuhongChen/panic3d-anime-reconstruction/issues/5#issuecomment-1493051485
