### ISSUE TITLE
no attribute 'run_dn_checkpoints' error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [ShuhongChen/panic3d-anime-reconstruction#29]
In the shuhongchen/panic3d-anime-reconstruction:latest docker, the following error occurred.

```
# python3 -m _scripts.eval.generate && python3 -m _scripts.eval.measure
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dl/panic3d/panic3d-anime-reconstruction/_scripts/eval/generate.py", line 38, in <module>
    rmline_model = rmline_wrapper.RMLineWrapper(('rmlineE_rmlineganA_n04', 199)).eval().to(device)
  File "/home/dl/panic3d/panic3d-anime-reconstruction/_train/img2img/util/rmline_wrapper.py", line 19, in __init__
    ckpt = userving.Checkpoint(*inferquery)
  File "/home/dl/panic3d/panic3d-anime-reconstruction/_util/serving_v1.py", line 17, in __init__
    self.im_ckpt = utraining.infer_module_checkpoint(run_name, ckpt)
  File "/home/dl/panic3d/panic3d-anime-reconstruction/_util/training_v1.py", line 191, in infer_module_checkpoint
    for fn in os.listdir(ir.run_dn_checkpoints)
AttributeError: 'NoneType' object has no attribute 'run_dn_checkpoints'
```

Please let me know how to fix it.

**Comment by tky5622** [comment]
more information on your env and what you tried would be appreciated.
I doubt you don't set PROJECT_DN. did you do this ?

>>Make a copy of ./_env/machine_config.bashrc.template to ./_env/machine_config.bashrc, and set $PROJECT_DN to the absolute path of this repository folder. The other variables are optional.

**Comment by Ishihara-Masabumi** [comment]
Thanks, but another error occurred.

```
$ export PROJECT_DN=/home/dl/panic3d/panic3d-anime-reconstruction
$ python3 -m _scripts.eval.generate && python3 -m _scripts.eval.measure
/home/dl/.local/lib/python3.8/site-packages/scipy/__init__.py:143: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 1.17.4)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
2023-06-14 10:44:26.282362: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-14 10:44:26.472127: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, imp, stat
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorboard-2.12.1-py3.8.egg/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.8/dist-packages/tensorboard-2.12.1-py3.8.egg/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd
/home/dl/.local/lib/python3.8/site-packages/jupyter_client/connect.py:27: DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
given by the platformdirs library.  To remove this warning and
see the appropriate new directories, set the environment variable
`JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
The use of platformdirs will be the default in `jupyter_core` v6
  from jupyter_core.paths import jupyter_data_dir
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/lib/python3.8/runpy.py:194 in _run_module_as_main                                           │
│                                                                                                  │
│   191 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   192 │   if alter_argv:                                                                         │
│   193 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 194 │   return _run_code(code, main_globals, None,                                             │
│   195 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   196                                                                                            │
│   197 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ /usr/lib/python3.8/runpy.py:87 in _run_code                                                      │
│                                                                                                  │
│    84 │   │   │   │   │      __loader__ = loader,                                                │
│    85 │   │   │   │   │      __package__ = pkg_name,                                             │
│    86 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  87 │   exec(code, run_globals)                                                                │
│    88 │   return run_globals                                                                     │
│    89                                                                                            │
│    90 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ /home/dl/panic3d/panic3d-anime-reconstruction/_scripts/eval/generate.py:11 in <module>           │
│                                                                                                  │
│     8 from _util.threedee_v0 import * ; import _util.threedee_v0 as u3d                          │
│     9 from _util.video_v1 import * ; import _util.video_v1 as uvid                               │
│    10                                                                                            │
│ ❱  11 import _train.eg3dc.util.eg3dc_v0 as ueg3d                                                 │
│    12 import _util.serving_v1 as userving                                                        │
│    13 from _util import sketchers_v2 as usketch                                                  │
│    14 from _util import eg3d_metrics3d as egm                                                    │
│                                                                                                  │
│ /home/dl/panic3d/panic3d-anime-reconstruction/_train/eg3dc/util/eg3dc_v0.py:20 in <module>       │
│                                                                                                  │
│   17                                                                                             │
│   18 import dnnlib                                                                               │
│   19 import legacy                                                                               │
│ ❱ 20 from camera_utils import LookAtPoseSampler, FOV_to_intrinsics                               │
│   21 from torch_utils import misc                                                                │
│   22 from training.triplane import TriPlaneGenerator                                             │
│   23                                                                                             │
│                                                                                                  │
│ /home/dl/panic3d/panic3d-anime-reconstruction/./_train/eg3dc/src/camera_utils.py:20 in <module>  │
│                                                                                                  │
│    17 import torch                                                                               │
│    18 import torch.nn as nn                                                                      │
│    19                                                                                            │
│ ❱  20 from training.volumetric_rendering import math_utils                                       │
│    21                                                                                            │
│    22 class GaussianCameraPoseSampler:                                                           │
│    23 │   """                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'training.volumetric_rendering'
```

**Comment by ShuhongChen** [comment]
Please set `$PROJECT_DN` in `./_env/machine_config.bashrc`
