### ISSUE TITLE
[question]#25 About the contents of front.pkl

### ISSUE THREAD

**Issue by TomoyaYamada194** [ShuhongChen/panic3d-anime-reconstruction#35]
Hello, Thank you for publishing this wonderful project.
I have a question about the answer to #25

I understood that the solution to #25 involves modifying generate.py to save the data from resnet_chonk into a pkl file, which can then be used for training. Consequently, I have altered generate.py and obtained the following data.

`"{'resnet_chonk': tensor([[[[-3.1723e+00, -3.1356e+00, -3.0122e+00,  ..., -3.0182e+00,
           -3.0302e+00, -3.0707e+00],
          [-3.1781e+00, -3.1504e+00, -2.9376e+00,  ..., -2.8380e+00,
           -2.8835e+00, -3.1385e+00],
          [-3.1517e+00, -2.9036e+00, -2.5128e+00,  ..., -1.6416e+00,
           -2.6505e+00, -3.0181e+00],
          ...,
          [ 1.1058e-01,  8.3331e-03, -6.3481e-01,  ...,  1.1358e-01,
           -3.2545e-01,  2.4348e-02],
          [ 6.4464e-02, -8.6739e-02, -4.0153e-01,  ...,  4.1071e-01,
           -2.2954e-01, -8.7458e-02],
          [ 1.4561e-01, -5.4080e-01,  3.4416e-02,  ..., -1.7221e-01,
            4.5234e-01, -4.2940e-01]]]], device='cuda:0')}`
            
I tried to use the data but got the following error

`Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dl/prodata/panic3d-anime-reconstruction/_train/eg3dc/trainers/train_eclustrousC.py", line 572, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/dl/prodata/panic3d-anime-reconstruction/_train/eg3dc/trainers/train_eclustrousC.py", line 567, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "/home/dl/prodata/panic3d-anime-reconstruction/_train/eg3dc/trainers/train_eclustrousC.py", line 112, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "/home/dl/prodata/panic3d-anime-reconstruction/_train/eg3dc/trainers/train_eclustrousC.py", line 61, in subprocess_fn
    getattr(training_loop, c.training_loop_version)(rank=rank, **c)
  File "/home/dl/prodata/panic3d-anime-reconstruction/./_train/eg3dc/src/training/training_loop_v0.py", line 284, in training_loop
    grid_size, images, labels = setup_snapshot_image_grid(training_set=training_set)
  File "/home/dl/prodata/panic3d-anime-reconstruction/./_train/eg3dc/src/training/training_loop_v0.py", line 74, in setup_snapshot_image_grid
    images, labels = zip(*[unpk(training_set[i]) for i in grid_indices])
  File "/home/dl/prodata/panic3d-anime-reconstruction/./_train/eg3dc/src/training/training_loop_v0.py", line 74, in <listcomp>
    images, labels = zip(*[unpk(training_set[i]) for i in grid_indices])
  File "/home/dl/prodata/panic3d-anime-reconstruction/_train/eg3dc/datasets/ecrutileE.py", line 49, in __getitem__
    x = self.ds[idx % len(self.ds)]
  File "/home/dl/prodata/panic3d-anime-reconstruction/_train/eg3dc/datasets/ecrutileE.py", line 368, in __getitem__
    'resnet_chonk': torch.tensor(uutil.pload(
RuntimeError: Could not infer dtype of dict
`
Can you please tell me the correct file contents of front.pkl?
Or if my understanding is wrong, please point it out to me.

**Comment by ShuhongChen** [comment]
Hi, thanks for your interest in our work; it seems like you're pickling the dict, but the dataloader expects only the tensor? Please try pickling only the tensor

**Comment by TomoyaYamada194** [comment]
Thank you for your reply.

I followed your instructions and created a pkl file that contains only the tensor.

`tensor([[[[-3.1681e+00, -3.1175e+00, -2.9860e+00,  ..., -3.0118e+00,
           -3.0287e+00, -3.0675e+00],
          [-3.1878e+00, -3.1382e+00, -2.8036e+00,  ..., -2.7311e+00,
           -2.8228e+00, -3.1219e+00],
          [-3.1572e+00, -2.9082e+00, -2.6042e+00,  ..., -2.4522e+00,
           -2.6248e+00, -3.0041e+00],
          ...,
          [ 1.0393e-01, -8.2370e-03, -1.1421e-01,  ...,  6.9643e-01,
           -3.1630e-01,  8.5664e-02],
          [ 9.6706e-02, -1.2832e-02, -5.3630e-01,  ..., -9.0855e-01,
           -9.0096e-01, -1.6158e-01],
          [ 7.6950e-02,  2.1208e-01,  5.1199e-01,  ...,  3.6749e-01,
            9.5654e-01, -3.1348e-02]]]], device='cuda:0')`

I tried to train it, but it outputs the following error

`Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dl/prodata/panic3d-anime-reconstruction/_train/eg3dc/trainers/train_eclustrousC.py", line 572, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/dl/prodata/panic3d-anime-reconstruction/_train/eg3dc/trainers/train_eclustrousC.py", line 567, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "/home/dl/prodata/panic3d-anime-reconstruction/_train/eg3dc/trainers/train_eclustrousC.py", line 112, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "/home/dl/prodata/panic3d-anime-reconstruction/_train/eg3dc/trainers/train_eclustrousC.py", line 61, in subprocess_fn
    getattr(training_loop, c.training_loop_version)(rank=rank, **c)
  File "/home/dl/prodata/panic3d-anime-reconstruction/./_train/eg3dc/src/training/training_loop_v0.py", line 284, in training_loop
    grid_size, images, labels = setup_snapshot_image_grid(training_set=training_set)
  File "/home/dl/prodata/panic3d-anime-reconstruction/./_train/eg3dc/src/training/training_loop_v0.py", line 74, in setup_snapshot_image_grid
    images, labels = zip(*[unpk(training_set[i]) for i in grid_indices])
  File "/home/dl/prodata/panic3d-anime-reconstruction/./_train/eg3dc/src/training/training_loop_v0.py", line 74, in <listcomp>
    images, labels = zip(*[unpk(training_set[i]) for i in grid_indices])
  File "/home/dl/prodata/panic3d-anime-reconstruction/_train/eg3dc/datasets/ecrutileE.py", line 116, in __getitem__
    resfeats = x['resnet_feats'][1].numpy()
TypeError: 'Dict' object is not callable
`

I commented out this section that I saw in response to #25.
> https://github.com/ShuhongChen/panic3d-anime-reconstruction/blob/d2cb8a0abbb523a91809d1522f6c44131ff14cec/_train/eg3dc/datasets/ecrutileE.py#L363-L365

Should I also comment out the part where this error appears?Would that improve things?
> https://github.com/ShuhongChen/panic3d-anime-reconstruction/blob/d2cb8a0abbb523a91809d1522f6c44131ff14cec/_train/eg3dc/datasets/ecrutileE.py#L116-L116

**Comment by ShuhongChen** [comment]
Oh yes, you should be able to remove `resnet_feats` from the dataloader completely, it probably isn't used anywhere during training; since `x` here is a `addict.Dict`, the not callable error actually is saying that there's no `resnet_feats` in x
