### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'base'

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [ShuhongChen/panic3d-anime-reconstruction#5]
When I run the 'python3 -m _scripts.generate && python3 -m _scripts.measure' command  line, the following error occurred.

```
$ python3 -m _scripts.generate && python3 -m _scripts.measure
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dl/panic3d/panic3d-anime-reconstruction/_scripts/generate.py", line 29, in <module>
    dk = dklustr.DatabackendMinna()
  File "/home/dl/panic3d/panic3d-anime-reconstruction/_databacks/lustrous_renders_v1.py", line 116, in __init__
    self.dn = f'{self.args.base.dn}/_data/lustrous'
AttributeError: 'dict' object has no attribute 'base'
```

Please tell me how to fix it.

**Comment by ShuhongChen** [comment]
> AttributeError: 'dict' object has no attribute 'base'

This seems like a dependency issue (missing addict python library).  Please run the commands from inside the docker container, which has the dependencies
