### ISSUE TITLE
Error Running Training Script

### ISSUE THREAD

**Issue by ETJeanMachine** [ShuhongChen/panic3d-anime-reconstruction#8]
Attempting to run the script: 
```
./_train/eg3dc/runs/ecrutileE_eclustrousC_n120/ecrutileE_eclustrousC_n120.sh
```
Results in the following error:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ericj/Source/panic3d-anime-reconstruction/_train/eg3dc/trainers/train_eclustrousC.py", line 572, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ericj/Source/panic3d-anime-reconstruction/_train/eg3dc/trainers/train_eclustrousC.py", line 348, in main
    c.training_set_kwargs, dataset_name = init_dataset_kwargs(data_class=opts.data_class, data_subset=opts.data_subset)
  File "/home/ericj/Source/panic3d-anime-reconstruction/_train/eg3dc/trainers/train_eclustrousC.py", line 125, in init_dataset_kwargs
    dataset_obj = dnnlib.util.construct_class_by_name(**dataset_kwargs) # Subclass of training.dataset.Dataset.
  File "/home/ericj/Source/panic3d-anime-reconstruction/./_train/eg3dc/src/dnnlib/util.py", line 305, in construct_class_by_name
    return call_func_by_name(*args, func_name=class_name, **kwargs)
  File "/home/ericj/Source/panic3d-anime-reconstruction/./_train/eg3dc/src/dnnlib/util.py", line 298, in call_func_by_name
    func_obj = get_obj_by_name(func_name)
  File "/home/ericj/Source/panic3d-anime-reconstruction/./_train/eg3dc/src/dnnlib/util.py", line 291, in get_obj_by_name
    module, obj_name = get_module_from_obj_name(name)
  File "/home/ericj/Source/panic3d-anime-reconstruction/./_train/eg3dc/src/dnnlib/util.py", line 262, in get_module_from_obj_name
    importlib.import_module(module_name) # may raise ImportError
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ericj/Source/panic3d-anime-reconstruction/_train/eg3dc/datasets/ecrutileE.py", line 27, in <module>
    from training.dataset import Dataset as DatasetEG3D
  File "/home/ericj/Source/panic3d-anime-reconstruction/./_train/eg3dc/src/training/dataset.py", line 247, in <module>
    import _databacks.lustrous_v0 as dkmodlust
ModuleNotFoundError: No module named '_databacks.lustrous_v0'
```

This is after I successfully run `make/shell_docker`. I presume there's an issue I'm having with python modules being recognized by python itself. Similarly, attempting to run the python command:
```
python3 -m _scripts.generate && python3 -m _scripts.measure
```
Generates a similar (albeit much smaller) error: 
```
/opt/conda/bin/python3: No module named _scripts.generate
```

Presumably Python is unable to figure out how the modules are set up here. Here's my system information I think that would be relevant to this issue.
```
Python Version:  3.8.12
which python: /opt/conda/bin/python (from within the docker)
which python: /usr/bin/python3 (from within my main terminal)
OS: Ubuntu 22.04.2 LTS x86_64
CPU: AMD Ryzen 9 5900X
GPU: NVIDIA GeForce RTX 3070 Ti
```

**Comment by h2440222798** [comment]
About no module named _scripts.generate  you should copy file from _scripts/eval/generate.py to _scripts/generate.py 
or you can try python3 -m ./scripts/generate.py command

**Comment by h2440222798** [comment]
_databacks.lustrous_v0 is not uploaded by author LOL

**Comment by ShuhongChen** [comment]
> or you can try python3 -m ./scripts/generate.py command

Yes, you're right; sorry about that, we put the scripts into an `eval` folder and forgot to change the documentation, should be updated now

> _databacks.lustrous_v0 is not uploaded by author LOL

We also forgot this file, sorry; uploaded now
